name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          # Wipe the server
          rm -rf ~/mieczkowski_website

          # Clone the repository
          git clone git@github.com:noveoko/mieczkowski_website.git ~/mieczkowski_website
          cd ~/mieczkowski_website
          git checkout main

          # Install the required packages
          # Assuming you have a requirements.txt file for pip packages, and you're using Python
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install -r requirements.txt

          # Start the application
          # I'm not sure how your app is started, so I'll use a generic command
          python3 app.py &
          sudo systemctl restart miecz
